name: Code Quality Checks

on:
  push:
    branches: [ main, develop, biome ]
  pull_request:
    branches: [ main, develop ]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Debug - Check Node and npm versions
      run: |
        node --version
        npm --version
        
    - name: Debug - List package.json scripts
      run: cat package.json | grep -A 10 '"scripts"'
        
    - name: Install dependencies
      run: |
        npm ci
        echo "Dependencies installed successfully"
      
    - name: Debug - Check installed packages
      run: npm list --depth=0
      
    - name: Run TypeScript compiler
      run: |
        echo "Running TypeScript build..."
        npm run build
        echo "Build completed successfully"
      
    - name: Run Biome checks
      run: |
        echo "Running Biome checks..."
        npm run ci
        echo "Biome checks completed successfully"

  security:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run security audit
      run: |
        echo "Running security audit..."
        npm audit --audit-level=moderate || echo "Audit completed with warnings"
        echo "Security check completed"